#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_index_main:
    path: /
    controller: App\Controller\IndexController::indexAction

app_posts:
    path: /post/create
    controller: App\Controller\PostsController::createAction

app_edit:
    path: /post/edit/{id}
    controller: App\Controller\PostsController::editAction
    requirements:
        id: \d+